
services:
  app1:
    image: kvinside/app-golang:2.1
    container_name: app1
    ports:
      - "9000:9000"
    environment:
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    networks:
      - app-network

  app2:
    image: kvinside/app-node:1.0
    container_name: app2
    ports:
      - "9100:9100"
    environment:
      NAME: app2
      PORT: 9100
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
